name: tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.20.0"

      - name: running unit-tests
        run: |
          go test -v ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --issues-exit-code=0
